### ISSUE TITLE
Reordering HAL command _OPCODES into mandatory and optional commands?

### ISSUE THREAD

**Issue by NormannMertigHitachiCambridge** [riverlane/QHAL#2]
Would it make sense to reorder _OPCODES in [HAL commands](https://github.com/riverlane/QHAL/blob/main/qhal/hal/_commands.py) into a code section of mandatory and a consecutive code section of optional commands? 

**Reason:** At the moment the list of optional commands is growing quite extensively making it hard to keep track of commands which must be supported by all partners. If partners keep adding optional commands to the list of _OPCODES it may become hard to identify the mandatory core commands from the code in the future.

**Comment by gabrielg42** [comment]
Hi @NormannMertigHitachiCambridge 

This is a good point. Can you please raise this as an issue in the [new repo](http://qhal.npl.co.uk/)? We can pick up the discussion there. 

Cheers!
