### ISSUE TITLE
Emulator specific commands

### ISSUE THREAD

**Issue by NormannMertigHitachiCambridge** [riverlane/QHAL#3]
Would it make sense to introduce emulator specific commands? Would it make sense to make these commands mandatory?

1. **Sample N shots** : Would sample N shots from the full qubit register after executing a quantum circuit.
2. **Probability in Zero** : Would return a vector of probabilities to have qubits 0,...,M-1 in zero state.

**Reason:**
- Saves computing effort for emulation based on state vector or density matrix propagation.
- Emulation may be equally important to a user.

**Comment by gabrielg42** [comment]
Hi @NormannMertigHitachiCambridge 

Can you please file a new issue for this in the [new repo](http://qhal.npl.co.uk/)? We can pick up the discussion there. 

Cheers!
